#!/usr/bin/env bash
# This script configures a server to make Nginx listen on port 80

# remove the default Ngnix configuration file
rm /etc/nginx/sites-enabled/default
# Configure Ngnix to listen on port 80 for all active IPv4 IPs
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# Restart Nginx
service nginx restart
