#!/usr/bin/env bash
# Congigure's an Nginx server to listen on port 80.

# This creates a symbolic link (-s option) between
# the Nginx configuration file and the enabled sites directory
ln -sf /ect/nginx/sites-abvailable/default /etc/nginx/sites-enabled/default
# restart nginx
service nginx start
#terminates the first snginx process ID
kill "$(pgrep 'nginx' | head -1)"
