#!/usr/bin/env bash
# Script loops 10 times with "bad luck", "good luck" at the 4th and 8th place
count=0
while((count<10))
do
	((count++))
	if [ ${count} -eq 4 ]; then
		echo "bad luck"
	elif [ ${count} -eq 8 ]; then
		echo "good luck"
	else
		echo "Best school"
	fi
done

