#!/usr/bin/env bash
# Script loops 10 times with "bad luck", "good luck" at the 4th and 8th place
count=0
while((count<10))
do
	echo "Best School"
	((count++))
	if [ ${count} -eq 3 ]; then
		echo "bad luck"
	elif [ $count -eq 7 ]; then
		echo "good luck"
	fi
done

